src/UI/Header.jsx
Changes Made:
- cleaned up code in Header.jsx component
- deleted unused import Grid
=> fix: header-component-cleanup

src/UI/ModuleStack.jsx
Changes Made:
- cleaned up code in ModuleStack component
- deleted unused imports Paper, List, ListItem, ListItemText
=> fix: module-stack-component-cleanup

src/App.css, src/UI/Header.css, src/UI/ModuleStackComponents/FlexibleBlock.css, src/index.css
Changes Made:
- cleaned up css files / formatting
=> fix: css-files-cleanup

src/UI/DynamicFormBuilder.jsx
Changes Made:
- cleaned up code in DynamicFormBuilder component
-deleted unused imports CustomSelect
- deleted random 
const options = [
{ value: "chocolate", label: "Chocolate" },
{ value: "strawberry", label: "Strawberry" },
{ value: "vanilla", label: "Vanilla" },
];
=> fix: dynamic-form-builder-component-cleanup

src/UI/TestingFormBuilder.jsx
Changes Made:
- Renamed module TestingFormBuilder to prevent conflict with other file DynamicFormBuilder (typo)
- cleaned up code in TestingFormBuilder component
=> fix: testing-form-builder-component-cleanup

src/UI/ModuleStackComponents/FlexibleBlock.jsx
- cleaned up code in FlexibleBlock component
- fixed type "PassivBlock" changed to "PassiveBlock"
=> fix: flexible-box-component-cleanup

src/UI/ViewerComponents/FileDropdown.jsx, src/UI/ViewerComponents/ProgressFileReader.jsx
Reverts ReproModel/repromodel#31
=> Revert "fix: viewer-components-cleanup"

src/UI/TrainingViewer.jsx
- cleaned up code in TrainingViewer component
- deleted unused import useEffect
- updated comments
=> fix: training-viewer-component-cleanup

src/UI/DynamicFormBuilder.jsx, src/UI/TestingFormBuilder.jsx, src/components/experiment-builder/experiment-builder.css, src/components/model-testing/model-testing.css
**Changes:**
- Created new component folders for tabs "Experiment Builder" and "Model Testing" to keep things separate and have a separate location for each page. We may want different stylings for different pages in the future.
- Replaced Form.css with individual css files experiment-builder.css and model-testing.css for now
- Updated imports
**Notes:**
- file DynamicFormBuilder.jsx will be moved to src > components > experiment-builder next
- file TestingFormBuilder.jsx will be moved to src > components > model-testing next
=> fix: Created new component folders for tabs "Experiment Builder" and "Model Testing" to keep things separate

src/UI/FormComponents/NewFlexibleFormField.jsx, src/components/ui/boolean-field.jsx, src/components/ui/default-text-field.jsx
Changes Made:
- extracted DefaultTextField and BooleanField components to src > components > ui so they can be found more easily and reused
- cleaned up FlexibleFormField.jsx / code formatting
=> fix: refactor-fields

src/App.jsx, src/UI/progress-viewer.jsx
Changes Made:
- renamed TestingViewer to ProgressViewer bc that is what the tab is labeled as in the UI
=> fix: rename-progress-viewer

src/App.jsx, src/components/experiment-builder/experiment-builder.jsx, src/components/model-testing/model-testing.jsx, src/components/progress-viewer/progress-viewer.jsx
Changes Made:
- **DynamicFormBuilder** component renamed **experiment-builder** to match UI and moved to folder src > components > experiment-builder to organize component and css in same folder.
- **TestingFormBuilder** component renamed **model-testing** to match UI and moved to folder src > components > model-testing to organize component and css in same folder.
- Moved **ProgressViewer** component to folder src > components > progress-viewer to organize all ProgressViewer-specific files in the same folder.
- Updated all imports / references.
=> fix: finish-refactoring

README.md
Changes Made:
- Fixed README typo preventing linking to file
=> fix: readme-typo

package-lock.json, package.json, src/components/custom-script/custom-script.jsx, src/components/ui/code-editor/code-editor.css, src/components/ui/code-editor/code-editor.jsx
First draft of CustomScript component:
- Created CustomScript component
- Created CodeEditor component
- Added "Copy" button that copies current state (content) of code editor to clipboard
- Added "Download" button
https://github.com/ReproModel/repromodel/assets/20110627/0c00eb30-2ef6-49d1-b998-e8c40e8d4024
=> feat: custom-script-component

repromodel_core/app.py, src/components/header/header.jsx, src/components/status-checks/status-checks.css, src/components/status-checks/status-checks.jsx
I created a small status check if the backend is up and running. Since sometimes when working on connecting front and backend the server crashed and I couldn't differentiate if it was just not working or down.
=> Feature: Status Checks

src/App.jsx, src/components/ui/code-editor/code-editor.css, src/components/ui/code-editor/code-editor.jsx
Changes Made:
- Fixed tab style "Custom Script" and moved to 4th tab
- Cleaned up code code-editor.jsx
- Fixed spacing issues in Custom Script tab.
Before:
After:
=> fix: custom-script-styles

src/components/status-checks/status-checks.css, src/components/status-checks/status-checks.jsx
Changes Made:
- Remove dead code.
- Cleanup status-checks.jsx
=> fix: cleanup-status-check

package-lock.json, package.json, repromodel_core/choices.json, src/App.jsx, src/components/llm-description/llm-description.css, src/components/llm-description/llm-description.jsx
Changes Made:
- set LLM output on axios.then()
- set radio buttons and LLM dropdown and additional prompt values on axios.then() because they get cleared onSubmit
- add loading animation
=> fix: set-llm-output

src/App.jsx
=> fix: resize-tab-buttons

src/App.jsx, src/components/custom-script/custom-script.css, src/components/custom-script/custom-script.jsx, src/components/llm-description/llm-description.jsx
Changes Made:
- Fixed dropdown to look better.
- Make more responsive to window resize.
=> fix: restyle-custom-script

src/components/custom-script/custom-script.jsx
Fix:
Forgot to fix category parameters on Submit and Download buttons. Updated now.
=> fix: custom-script-buttons

src/components/experiment-builder/experiment-builder.jsx
fixed: submit-for-training-text
=> fixed: submit-for-training-text

repromodel_core/app.py
Changes Made:
- Cleaned up app.py code and comments.
=> refactor: cleanup-app-script

repromodel_core/app.py, repromodel_core/data/dummyData/generate_data.py
Changes Made:
- Cleaned up generate_data.py and make more readable.
=> refactor: cleanup-generate-data

repromodel_core/demotrainer.py
Changes Made:
- Cleaned up demotrainer.py
=> refactor: cleanup-demotrainer

LICENSE.md
Changes Made:
Replaced
Copyright (c) Soumith Chintala 2016, All rights reserved.
Copyright 2019 Ross Wightman
with
Copyright (c) ReproModel
=> fix: fixed-typo-license

LICENSE.md
- Added links to TorchVision and PyTorch Image Models licenses.
=> fix: update-license

README.md
Changes Made:
- Added Discord invite link
- Got rid of rate limit message
=> documentation: readme-discord

repromodel_core/choices.json, repromodel_core/generate_choices.py
Changes Made:
- Cleaned up generate_choices.py
- Added comments to make the file easier to read and understand.
=> refactor: cleanup-generate-choices

src/components/first-time-modal/first-time-modal.jsx
Changes Made:
- Fixed config rename that caused error.
=> fix: train-config-rename

src/utils/json-helpers.jsx
Implemented the fix for the bug with unnecessary config params
=> Clean Config on Submit

README.md
- Removed "On Mac and Linux" comment. Makes no sense since you put next to the npm command anyway.
- Fixed typo "there" to "their".
=> documentation: fixed-readme

README.md
=> documentation: fixed-readme-typo

src/App.jsx, src/components/extract-code/extract-code.css, src/components/extract-code/extract-code.jsx
=> feat: extract-code-v2

repromodel_core/app.py, repromodel_core/choices.json, src/components/extract-code/extract-code.jsx, src/components/ui/file-reader/file-reader.jsx
Changes Made:
- Added axios calls to **/copy-covered-files** and **/create-repo**
- Added required field validation.
- Fixed file-reader.jsx bug
Tested GitHub push. It seems to work.
=> feat: code-extractor-axios-call

src/components/custom-script/custom-script.css, src/components/custom-script/custom-script.jsx
Changes:
- got rid of 'and' keyword in placeholder text
- added margin around script code
=> fix: custom-script-restyle

repromodel_core/app.py, src/components/experiment-builder/experiment-builder.jsx, src/components/model-testing/model-testing.jsx, src/utils/json-helpers.jsx
Changes Made:
Added endpoint: /kill-training-process
Added endpoint: /kill-testing-process
Updated UI to show/hide Train/Stop Train and Test / Stop Test based on /ping response
=> feat: kill-process

src/App.jsx, src/components/status-checks/status-checks.jsx
fontSize: "9px", width: "16.66%"
=> fix: fixed-tab-proportions

src/App.jsx, src/components/modality-section/modality-options.css, src/components/modality-section/modality-section.jsx
=> fix: modality-card-styles

src/components/modality-section/image-urls.jsx
Changes:
- Added some more images.
=> fix: update-images

src/App.css, src/App.jsx, src/components/first-time-modal/first-time-modal.jsx, src/components/header/header.jsx
=> fix: restyle-header-and-tabs

src/components/progress-viewer/progress-viewer.css, src/components/progress-viewer/progress-viewer.jsx, src/components/ui/file-dropdown.jsx, src/components/ui/file-reader/file-reader.css, src/components/ui/file-reader/file-reader.jsx
Changes:
- Restyled progress viewer / added some text.
- Load command_output.txt on page load
=> fix: update-progress-viewer

src/App.css, src/App.jsx, src/components/custom-script/custom-script.css, src/components/custom-script/custom-script.jsx, src/components/experiment-builder/experiment-builder.jsx, src/components/extract-code/extract-code.css, src/components/extract-code/extract-code.jsx, src/components/first-time-modal/first-time-modal.css, src/components/first-time-modal/first-time-modal.jsx, src/components/header/header.jsx, src/components/llm-description/llm-description.css, src/components/llm-description/llm-description.jsx, src/components/modality-section/modality-options.css, src/components/modality-section/modality-section.jsx, src/components/model-testing/model-testing.css, src/components/model-testing/model-testing.jsx, src/components/progress-viewer/progress-viewer.css, src/components/progress-viewer/progress-viewer.jsx, src/components/status-checks/status-checks.css
=> fix: updated-all-styles

src/App.css, src/components/custom-script/custom-script.css, src/components/experiment-builder/experiment-builder.jsx, src/components/first-time-modal/first-time-modal.jsx, src/components/progress-viewer/progress-viewer.css, src/components/progress-viewer/progress-viewer.jsx, src/components/ui/file-reader/file-reader.css
- removed some dead css
- added cursor pointer
- resize text
=> fix: more css styles

src/components/custom-script/custom-script.css, src/components/custom-script/custom-script.jsx
=> fix: remove-copy-button

src/components/llm-description/llm-description.css, src/components/llm-description/llm-description.jsx
Changes:
- Remove copy on LLM page
=> fix: remove-llm-copy

src/components/custom-script/custom-script.jsx, src/components/llm-description/llm-description.jsx
=> fix: add-tooltip

repromodel_core/app.py, src/components/custom-script/custom-script.css, src/components/custom-script/custom-script.jsx, src/utils/json-helpers.jsx
Changes Made:
- add download path to alert() msg
- remove second download button
- fixed css styles
=> fix: add download path to alert() msg / remove second download button

src/components/custom-script/custom-script.css, src/components/experiment-builder/experiment-builder-wrapper.css, src/components/modality-section/image-urls.jsx, src/components/modality-section/modality-options.css, src/components/modality-section/modality-section.jsx
=> fix: modality-urls / modality card styles

src/App.jsx
=> fix: slider over tab bug

src/components/custom-script/custom-script.css, src/components/custom-script/custom-script.jsx, src/components/experiment-builder/experiment-builder-wrapper.jsx, src/components/extract-code/extract-code.css, src/components/llm-description/llm-description.jsx, src/components/ui/boolean-field.jsx, src/components/ui/custom-select.jsx, src/components/ui/default-text-field.jsx, src/components/ui/file-dropdown.jsx, src/components/ui/float-field.jsx, src/components/ui/formula-field.jsx, src/components/ui/integer-field.jsx, src/components/ui/string-field.jsx
Changes Made:
- Make input fields gray
=> feat: dark-mode-ii

src/components/custom-script/custom-script.css, src/components/llm-description/llm-description.css, src/components/llm-description/llm-description.jsx
Changes Made:
- Fixed loading spinner bug
- Change text white on gray background.
=> feat: color-change-iii

repromodel_core/app.py, src/App.jsx, src/components/model-testing/model-testing.jsx, src/utils/json-helpers.jsx
@dsitnik please check if that is matching the specs.
=> Implement feature

src/components/model-testing/model-testing.jsx
@dsitnik please see here the new testing edits to add params for models, datasets and augmentations
=> Add models, augmentations and dataset params for testing.
